name: Latest blog post workflow
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 8 * * *"
  workflow_dispatch:
permissions:
      contents: write

jobs:
  update-readme-with-youtube:
    name: Update this repo's index.html with latest blog titles from blogspot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://learningcurves.hashnode.dev/rss.xml"
